<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>

    <IsRoslynComponent>true</IsRoslynComponent>
    <EnforceExtendedAnalyzerRules>true</EnforceExtendedAnalyzerRules>
    <GeneratePackageOnBuild>true</GeneratePackageOnBuild>
    <IncludeBuildOutput>false</IncludeBuildOutput>
    <NoWarn>NU5128</NoWarn>
    <GenerateDocumentationFile>true</GenerateDocumentationFile>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <OutputPath>./nupkg</OutputPath>
    <DebugType>portable</DebugType>

    <Title>Scene Helpers</Title>
    <Version>0.0.2</Version>
    <Description>Generates scene paths for Godot C# projects.</Description>
    <Copyright>© 2026 Mark DiBarry</Copyright>
    <Authors>Mark DiBarry</Authors>
    <Company>Mark DiBarry</Company>

    <PackageId>GameCore.SceneHelpers</PackageId>
    <PackageReleaseNotes>Reorganized namespace</PackageReleaseNotes>
    <PackageIcon>icon.png</PackageIcon>
    <PackageTags>generator;utilities;godot;gamedev</PackageTags>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <PackageLicenseFile>LICENSE</PackageLicenseFile>
    <PackageProjectUrl>https://github.com/markdibarry/SceneHelpers</PackageProjectUrl>

    <RepositoryType>git</RepositoryType>
    <RepositoryUrl>https://github.com/markdibarry/SceneHelpers.git</RepositoryUrl>
  </PropertyGroup>

  <ItemGroup>
    <None Include="../../README.md" Pack="true" PackagePath="\" />
    <None Include="../../LICENSE" Pack="true" PackagePath="\" />
    <None Include="../../icon.png" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="GodotSharp" Version="4.5.0" />
    <ProjectReference Include="../GameCore.SceneHelpers.Core/GameCore.SceneHelpers.Core.csproj" Pack="false" PrivateAssets="all"/>
    <ProjectReference Include="../GameCore.SceneHelpers.Generator/GameCore.SceneHelpers.Generator.csproj" Pack="false" PrivateAssets="all"/>
  </ItemGroup>

  <ItemGroup>
    <None Include="$(OutputPath)\GameCore.SceneHelpers.Core.dll" Pack="true" PackagePath="lib/net8.0/" />
    <None Include="$(OutputPath)\GameCore.SceneHelpers.Generator.dll" Pack="true" PackagePath="analyzers/dotnet/cs/" />
  </ItemGroup>
</Project>