using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace GameCore.SceneHelpers.Generator;

/// <summary>
/// A generator to add static Godot node scene paths at design time.
/// </summary>
[Generator]
public class ScenePathGenerator : IIncrementalGenerator
{
    private static readonly SymbolDisplayFormat FullyQualifiedNoGlobal = SymbolDisplayFormat.FullyQualifiedFormat
        .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted)
        .WithMemberOptions(SymbolDisplayMemberOptions.IncludeContainingType);

    /// <summary>
    /// Initialize method for the Scene Path generator.
    /// </summary>
    /// <param name="context"></param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var godotClassesProvider = context.SyntaxProvider
            .CreateSyntaxProvider<(ClassDeclarationSyntax, INamedTypeSymbol)?>(
                predicate: static (n, _) => n is ClassDeclarationSyntax cds && cds.IsPartial() && !cds.IsNested(),
                transform: static (ctx, _) =>
                {
                    var cds = (ClassDeclarationSyntax)ctx.Node;
                    INamedTypeSymbol? symbol = ctx.SemanticModel.GetDeclaredSymbol(cds);

                    if (symbol?.BaseType == null || !symbol.BaseType.InheritsFrom("GodotSharp", "Godot.Node"))
                        return null;

                    if (Path.GetFileNameWithoutExtension(cds.SyntaxTree.FilePath) != symbol.Name)
                        return null;

                    return (cds, symbol);
                })
            .Where(x => x is not null)
            .Select((x, _) => x!.Value)
            .Collect();
        var projectRootProvider = context.AnalyzerConfigOptionsProvider
            .Select((prov, _) =>
            {
                if (prov.GlobalOptions.TryGetValue("build_property.GodotProjectDir", out var dir) && !string.IsNullOrWhiteSpace(dir))
                    return dir;
                if (prov.GlobalOptions.TryGetValue("build_property.ProjectDir", out dir) && !string.IsNullOrWhiteSpace(dir))
                    return dir;
                return null;
            });
        var combined = godotClassesProvider.Combine(projectRootProvider);
        context.RegisterSourceOutput(combined, VisitGodotScriptClass);
    }

    private static void VisitGodotScriptClass(
        SourceProductionContext spc,
        (ImmutableArray<(ClassDeclarationSyntax, INamedTypeSymbol)> Classes, string? GodotProjectDir) data)
    {
        if (string.IsNullOrWhiteSpace(data.GodotProjectDir))
            return;

        string projectDir = data.GodotProjectDir!;

        foreach ((ClassDeclarationSyntax cds, INamedTypeSymbol symbol) in data.Classes)
        {
            string ns = string.Empty;

            if (!symbol.ContainingNamespace.IsGlobalNamespace)
                ns = $"namespace {symbol.ContainingNamespace.ToDisplayString()};\n";

            string tscnPath = GetTscnPath(cds.SyntaxTree.FilePath, projectDir);
            string sourceText = $$"""
            // <auto-generated>
            using Godot;
            using GameCore.SceneHelpers;

            {{ns}}
            public partial class {{symbol.Name}} : IScene
            {
            #pragma warning disable CS0108
                public static string TscnPath => "{{tscnPath}}";
                public static PackedScene LoadPackedScene() => GD.Load<PackedScene>(TscnPath);
                public static {{symbol.Name}} Instantiate() => LoadPackedScene().Instantiate<{{symbol.Name}}>();
            #pragma warning restore CS0108
            }
            """;

            string hintName = symbol
                .ToDisplayString(NullableFlowState.NotNull, FullyQualifiedNoGlobal)
                // AddSource() doesn't support @ prefix
                .Replace("@", "")
                // AddSource() doesn't support angle brackets
                .Replace("<", "(Of ")
                .Replace(">", ")");

            spc.AddSource(hintName + "_ScenePath.g", SourceText.From(sourceText, Encoding.UTF8));
        }
    }

    private static string GetTscnPath(string path, string dir)
    {
        // Make sure the directory ends with a path separator
        dir = Path.Combine(dir, " ").TrimEnd();

        if (Path.DirectorySeparatorChar == '\\')
            dir = dir.Replace("/", "\\") + "\\";

        var fullPath = new Uri(Path.ChangeExtension(Path.GetFullPath(path), ".tscn"), UriKind.Absolute);
        var relRoot = new Uri(Path.GetFullPath(dir), UriKind.Absolute);

        // MakeRelativeUri converts spaces to %20, hence why we need UnescapeDataString
        return "res://" + Uri.UnescapeDataString(relRoot.MakeRelativeUri(fullPath).ToString());
    }
}

internal static class ExtensionMethods
{
    internal static bool IsNested(this TypeDeclarationSyntax cds)
        => cds.Parent is TypeDeclarationSyntax;

    internal static bool IsPartial(this TypeDeclarationSyntax cds)
        => cds.Modifiers.Any(SyntaxKind.PartialKeyword);

    internal static bool InheritsFrom(this ITypeSymbol? symbol, string assemblyName, string typeFullName)
    {
        while (symbol != null)
        {
            if (symbol.ContainingAssembly?.Name == assemblyName &&
                symbol.FullQualifiedNameOmitGlobal() == typeFullName)
            {
                return true;
            }

            symbol = symbol.BaseType;
        }

        return false;
    }

    private static string FullQualifiedNameOmitGlobal(this ITypeSymbol symbol)
        => symbol.ToDisplayString(NullableFlowState.NotNull, FullyQualifiedFormatOmitGlobal);

    private static SymbolDisplayFormat FullyQualifiedFormatOmitGlobal { get; } =
        SymbolDisplayFormat.FullyQualifiedFormat
            .WithGlobalNamespaceStyle(SymbolDisplayGlobalNamespaceStyle.Omitted)
            .WithMemberOptions(SymbolDisplayMemberOptions.IncludeContainingType);
}

