using System;
using System.Collections.Immutable;
using System.IO;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace ScenePathGenerator;

/// <summary>
/// A generator to add static Godot node scene paths at design time.
/// </summary>
[Generator]
public class ScenePathGenerator : IIncrementalGenerator
{
    /// <summary>
    /// Initialize method for the Scene Path generator.
    /// </summary>
    /// <param name="context"></param>
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var classDecls = context.SyntaxProvider
            .CreateSyntaxProvider(
                predicate: static (x, _) => x is ClassDeclarationSyntax cds && cds.Modifiers.Any(m => m.IsKind(SyntaxKind.PartialKeyword)),
                transform: static (x, _) => (ClassDecl: (ClassDeclarationSyntax)x.Node, Semantic: x.SemanticModel))
            .Where(static x => x.ClassDecl != null);
        var compilationAndClasses = context.CompilationProvider.Combine(classDecls.Collect());
        var projectRootProvider = context.AnalyzerConfigOptionsProvider
            .Select((prov, _) =>
            {
                if (prov.GlobalOptions.TryGetValue("build_property.GodotProjectDir", out var v) && !string.IsNullOrWhiteSpace(v))
                    return v;
                if (prov.GlobalOptions.TryGetValue("build_property.ProjectDir", out v) && !string.IsNullOrWhiteSpace(v))
                    return v;
                return null;
            });
        var combined = compilationAndClasses.Combine(projectRootProvider);
        context.RegisterSourceOutput(combined, FindAndGenerate);
    }

    private static void FindAndGenerate(
        SourceProductionContext spc,
        (
            (Compilation Comp, ImmutableArray<(ClassDeclarationSyntax cds, SemanticModel semModel)> Classes)
            CompAndClasses,
            string? ProjectRoot
        ) data)
    {
        Compilation compilation = data.CompAndClasses.Comp;
        var classes = data.CompAndClasses.Classes;
        string projectRoot = data.ProjectRoot ?? "";

        if (classes == null || classes.Length == 0)
            return;

        INamedTypeSymbol? nodeBaseType = compilation.GetTypeByMetadataName("Godot.Node");

        if (nodeBaseType == null)
            return;

        foreach ((ClassDeclarationSyntax? cds, SemanticModel? semModel) in classes)
        {
            if (semModel.GetDeclaredSymbol(cds) is not INamedTypeSymbol classSymbol)
                continue;

            bool isNodeClass = false;
            INamedTypeSymbol? baseType = classSymbol.BaseType;

            while (baseType != null)
            {
                if (SymbolEqualityComparer.Default.Equals(baseType.OriginalDefinition, nodeBaseType))
                {
                    isNodeClass = true;
                    break;
                }

                baseType = baseType.BaseType;
            }

            if (!isNodeClass)
                continue;

            string ns = string.Empty;

            if (!classSymbol.ContainingNamespace.IsGlobalNamespace)
                ns = $"namespace {classSymbol.ContainingNamespace.ToDisplayString()};\n";

            string filePath = cds.SyntaxTree.FilePath;

            if (!filePath.EndsWith(".cs"))
                continue;

            string tscnPath = GetTscnPath(cds.SyntaxTree.FilePath, projectRoot);
            string sourceText = $$"""
            // <auto-generated>
            using Godot;

            {{ns}}
            public partial class {{classSymbol.Name}}
            {
                public static string ScenePath => "{{tscnPath}}";

                public static PackedScene GetScene() => GD.Load<PackedScene>(ScenePath);

                public static {{classSymbol.Name}} Instantiate() => GetScene().Instantiate<{{classSymbol.Name}}>();
            }
            """;

            spc.AddSource($"{classSymbol.Name}.g.cs", SourceText.From(sourceText, Encoding.UTF8));
        }
    }

    private static string GetTscnPath(string path, string dir)
    {
        // Make sure the directory ends with a path separator
        dir = Path.Combine(dir, " ").TrimEnd();

        if (Path.DirectorySeparatorChar == '\\')
            dir = dir.Replace("/", "\\") + "\\";

        var fullPath = new Uri(Path.ChangeExtension(Path.GetFullPath(path), ".tscn"), UriKind.Absolute);
        var relRoot = new Uri(Path.GetFullPath(dir), UriKind.Absolute);

        // MakeRelativeUri converts spaces to %20, hence why we need UnescapeDataString
        return "res://" + Uri.UnescapeDataString(relRoot.MakeRelativeUri(fullPath).ToString());
    }
}
